### ISSUE TITLE
Check out Vundle

### ISSUE THREAD

**Issue by kevinSuttle** [mahemoff/dotfiles#1]
Much cleaner than Pathogen. At least to me. :)

https://github.com/gmarik/vundle

My vim dotfiles
https://github.com/kevinSuttle/dotfiles/blob/master/install.zsh#L22
https://github.com/kevinSuttle/dotfiles/blob/master/vimrc#L3
https://github.com/kevinSuttle/dotfiles/blob/master/vimrc.bundles

**Comment by mahemoff** [comment]
Just noticed this, thanks, will look at Vundle if I ever do a major Vim refactor.
